# Generated by Django 4.0.6 on 2022-07-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ativo',
        ),
    ]
