# Generated by Django 4.0.6 on 2022-07-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_inferior_product_superior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=220)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=220)),
                ('inferior', models.FloatField()),
                ('superior', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='salesman',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
