# Generated by Django 4.0.6 on 2022-07-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_info_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='task',
        ),
    ]
