# Generated by Django 4.0.6 on 2022-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_info_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='editar_time_interval',
            field=models.CharField(choices=[('1 min', '1 min'), ('5 mins', '5 mins'), ('1 hour', '1 hour')], default='5 mins', max_length=255),
        ),
    ]
