# Generated by Django 4.0.6 on 2022-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_info_editar_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='editar_time_interval',
            field=models.CharField(choices=[('1 min', '1 min'), ('5 mins', '5 mins'), ('1 hour', '1 hour'), ('editar', 'editar')], default='editar', max_length=255),
        ),
    ]
